const CACHE='chokin-v0914-new-cats';
const ASSETS=['./','./index.html','./favicon.svg','./icons/icon-192.png','./icons/icon-512.png','./icons/icon-maskable-512.png','./icons/apple-touch-icon.png','./styles.css','./fixes.css','./v021-quick.css','./v03-scenes.css','./v04-canvas.css','./v05-fever.css','./v05-controls.css','./v051-polish.css','./v06-cats.css','./v08-collection.css','./v092-save-spectacle.css','./v093-assets.css','./v097-calendar.css','./v098-goal.css','./v099-goal-history.css','./v0910-badges.css','./v0911-restore-preview.css','./v0912-onboarding.css','./v0913-daily-note.css','./visual-assets.js','./cat-image-processor.js','./onboarding.js','./cat-collection.js','./cat-coins.js','./daily-note.js','./cat-characters.js','./game-effects.js','./asset-loader.js','./canvas-effects.js','./goal-history.js','./savings-goal.js','./badges.js','./restore-preview.js','./app.js','./assets/manifest.json','./assets/cats/cat-catalog.json','./assets/cats-transparent/cat_celebrate.png','./assets/cats-transparent/cat_black.png','./assets/cats-transparent/cat_calico.png','./assets/cats-transparent/cat_orange_tabby.png','./assets/cats-transparent/cat_hachiware.png','./assets/cats-transparent/cat_gray.png','./assets/cats-transparent/cat_surprised.png','./assets/cats-transparent/cat_ninja.png','./assets/cats-transparent/cat_wizard.png','./assets/cats-transparent/cat_detective.png','./assets/cats-transparent/cat_chef.png','./assets/cats-transparent/cat_cosmic.png','./assets/cats-transparent/cat_samurai.png','./assets/cats-transparent/cat_pirate.png','./assets/cats-transparent/cat_knight.png','./assets/cats-transparent/cat_angel.png','./assets/cats-transparent/cat_dragon.png','./assets/cats-transparent/cat_royal.png','./assets/cats-transparent/cat_deity.png','./assets/cats/cat_angel.png','./assets/cats/cat_black.png','./assets/cats/cat_calico.png','./assets/cats/cat_celebrate.png','./assets/cats/cat_chef.png','./assets/cats/cat_cosmic.png','./assets/cats/cat_deity.png','./assets/cats/cat_detective.png','./assets/cats/cat_dragon.png','./assets/cats/cat_gray.png','./assets/cats/cat_hachiware.png','./assets/cats/cat_knight.png','./assets/cats/cat_ninja.png','./assets/cats/cat_orange_tabby.png','./assets/cats/cat_pirate.png','./assets/cats/cat_royal.png','./assets/cats/cat_samurai.png','./assets/cats/cat_surprised.png','./assets/cats/cat_wizard.png','./assets/coins/cat_coin.png','./assets/scenes/necessary_expense_stamp_cat.png','./manifest.webmanifest'];
ASSETS.push('./assets/cats-transparent/cat_gardener.png','./assets/cats-transparent/cat_ranger.png','./assets/cats-transparent/cat_idol.png');
self.addEventListener('install',event=>event.waitUntil(caches.open(CACHE).then(cache=>cache.addAll(ASSETS))));
self.addEventListener('activate',event=>event.waitUntil(Promise.all([caches.keys().then(keys=>Promise.all(keys.filter(key=>key.startsWith('chokin-')&&key!==CACHE).map(key=>caches.delete(key)))),self.clients.claim()])));
self.addEventListener('message',event=>{if(event.data?.type==='SKIP_WAITING')self.skipWaiting();});
self.addEventListener('fetch',event=>{
  if(event.request.method!=='GET')return;
  const url=new URL(event.request.url),isCatImage=url.pathname.match(/\/assets\/cats(?:-transparent)?\//)&&/\.(png|webp)$/i.test(url.pathname),isCatData=url.pathname.endsWith('/cat-characters.js')||url.pathname.endsWith('/cat-catalog.json'),isAsset=url.pathname.includes('/assets/');
  if(isCatData){event.respondWith(fetch(event.request).then(response=>{if(response.ok)caches.open(CACHE).then(cache=>cache.put(event.request,response.clone()));return response;}).catch(()=>caches.match(event.request,{ignoreSearch:true})));return;}
  if(isCatImage){event.respondWith(caches.match(event.request,{ignoreSearch:true}).then(cached=>{const refresh=fetch(event.request).then(response=>{if(response.ok)caches.open(CACHE).then(cache=>cache.put(event.request,response.clone()));return response;}).catch(()=>cached);return cached||refresh;}));return;}
  if(isAsset){event.respondWith(fetch(event.request).then(response=>{if(response.ok)caches.open(CACHE).then(cache=>cache.put(event.request,response.clone()));return response;}).catch(()=>caches.match(event.request,{ignoreSearch:true})));return;}
  event.respondWith(caches.match(event.request,{ignoreSearch:true}).then(cached=>cached||fetch(event.request).then(response=>response.ok?response:Promise.reject(new Error(`HTTP ${response.status}`))).catch(()=>event.request.mode==='navigate'?caches.match('./index.html'):undefined)));
});
